.TH FCR 1 "September 2026" "fcr" "User Commands"

.SH NAME
fcr \- concatenate files and print on the standart output.

.SH SYNOPSIS
.b fcr
.RI [OPTION] [-n] [-b]

.SH DESCRIPTION
concatenate files and print on the standart output.

.SH OPTIONS
.TP
.BR \-n ", " \-\-number
Number all output lines.

.TP
.BR \-b ", " \-\-number\-nonblank
Number only nonempty output lines.

.SH AUTHOR
Written as C++ implementation of the Linux cat command.